invest:
  enabled: true
  connector:
    token: {TOKEN}
  rate-limiter:
    requests-per-second: 10
    requests-per-minute: 200
    timeout-ms: 30000

ru:
  invest:
    api:
      stock:
        supplier:
          scheduler:
            bond:
              enabled: true
              cron: "0 0 3 * * *"
            coupon:
              enabled: true
              cron: "0 30 3 * * *"

spring:
  cache:
    type: caffeine
  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true
      client:
        config:
          cb-rf-client:
            enabled: true
            url: https://www.cbr.ru/
          budget-org-client:
            enabled: true
            url: https://api.budjet.org/
  datasource:
    hikari:
      connection-test-query: select 1
      connection-init-sql: SET search_path TO invest_api_test
      connection-timeout: 30000
      driver-class-name: org.postgresql.Driver
      idle-timeout: 30000
      max-lifetime: 40000
      maximum-pool-size: 15
      minimum-idle: 15
      pool-name: postgres
      password: password
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    parameters:
      appUsername: ${spring.datasource.hikari.username}
      schema: invest_api_test
      sql_schema: invest_api_test
    enabled: true
    default-schema: invest_api_test

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
